###############################################################################
#
# Environment for makerules
#

StrategyLib = ..
subdirs     =	two-sorts-drift-default	\
		little-lambda \
		joos-padl02 \
		joos-rule02 \
		two-sorts-deriving \
		haskell


###############################################################################
#
# Reusable includes
#

include ${StrategyLib}/scripts/makerules.all
include ${StrategyLib}/scripts/makerules.clean
include ${StrategyLib}/scripts/makerules.check
include ${StrategyLib}/scripts/makerules.recurse
