###############################################################################
#
# Environment for makerules
#

StrategyLib = ../..
derive      = DatatypesTermInstances.hs
Model       = drift-default
subdirs     = testsuite


###############################################################################
#
# Reusable includes
#

include ${StrategyLib}/scripts/makerules.examples

