# refer to StrategyLib top-level directory
StrategyLib = ../..
Model       = drift-default

# list the modules to be derived with DrIFT
derive=DatatypesTermInstances.hs

# include the reusable makerules
include ${StrategyLib}/scripts/makerules.examples
